---
title: "Väikesel korpusel morfoloogiliste ja süntaktiliste tunnuste mõjud veebitekstide spontaansuse ja formaalsuse inimhinnangutele"
author: Karl Gustav Gailit
output: html_notebook:
    df_print: paged
---

# Pakettide laadimine ja eelseadistus

```{r}
library(corrplot)
library(randomForest)
library(lmtest)
# Suurendan lubatud mälukasutuse arvu (allikad:https://stackoverflow.com/questions/32826906/how-to-solve-protection-stack-overflow-issue-in-r-studio ja https://www.researchgate.net/post/error_protect_protection_stack_overflow_in_R)
options(expressions = 5e5)
memory.limit(size=8000000)

# Määran kordavuse jaoks seemne
set.seed(100)

# Loe fail sisse
dat <- read.csv(file = 'Randmestik.csv', encoding = "UTF-8")
#Asenda vigaselt imporditud nimi
names(dat)[names(dat) == "nud.partitsiibiga_verbide_osakaal"] <- "nudpartitsiibiga_verbide_osakaal"
```

# Juhumetsad

## Juhumetsade koostamine

```{r}
# Juhumets logaritmimisega (kasutatud lineaarse regressiooni tunnuste valimiseks)
m.mets.form.log <- randomForest(formaalsus ~  TTR + asesõnade_esimese_isiku_osaarv + asesõnade_kolmanda_isiku_osaarv + asesõnade_teise_isiku_osaarv + emotikonide_arv + kaudse_kõneviisi_osakaal + lemmapikkuse_osaarv  + käändsõnade_osaarv + leksikonides_esinevade_osaarv + nudpartitsiibiga_verbide_osakaal + passiivi_osakaal + verbide_esimese_isiku_osaarv + verbide_kolmanda_isiku_osaarv + verbide_teise_isiku_osaarv, 
                            data = dat,
                            importance = TRUE)
m.mets.spon.log <- randomForest(spontaansus ~ TTR + asesõnade_esimese_isiku_osaarv + emotikonide_arv + lemmapikkuse_osaarv + kokkukleepunud_kirjavahemärkide_arv + korduvate_juppide_arv + käändsõnade_osaarv + leksikonides_esinevade_osaarv + läbinisti_suur + puuduva_suure_algustähega + tajuverbide_osaarv,
                            data = dat,
                            importance = TRUE)
```

## Juhumetsade analüüs

### Formaalsus

```{r}
#Formaalsuse analüüs kirjalikult
m.mets.form.log
importance(m.mets.form.log)
```

```{r}
# Juhumetsa info joonisel
# Esimene joonis failis "juhumetsadeInfoLog.pdf"
jpeg(file="saving_plot1.jpeg", width = 1200, height=500)
varImpPlot(m.mets.form.log)
dev.off()
```

### Spontaansus

```{r}
#Spontaansuse analüüs kirjalikult
m.mets.spon.log
importance(m.mets.spon.log)
```

```{r}
# Juhumetsa info joonisel
# Teine joonis failis "juhumetsadeInfoLog.pdf"
jpeg(file="saving_plot2.jpeg", width = 1200, height=500)
varImpPlot(m.mets.spon.log)
dev.off()
```
